baseURL = "http://example.org/"
languageCode = "en-us"
title = "Independent Impact"

[menu]
  [[menu.main]]
    name = "Impact Framework"
    url = "/impact-framework/"
    weight = 1
  [[menu.main]]
    name = "Our Story"
    url = "/our-story/"
    weight = 2
  [[menu.main]]
    name = "Get Started"
    url = "/get-started/"
    weight = 3
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/how-to-engage/"
    weight = 5
