baseURL = "https://independentimpact.org/"
languageCode = "en-us"
title = "Independent Impact"

# Theme Config
theme = "hugo-saasify-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = "Independent Impact"
  author = "Nova Institute"
  logo = "/images/IILOGO1.png"
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  # googleAnalytics = "G-XXXXXXXXXX"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Independent Impact"
    description = "A platform for transparent, reputation-led impact accounting."
    gradient_from = "#2563eb"  # Indigo-600
    gradient_to = "#7c3aed"    # Purple-600
    gradient_angle = 30
    [params.cta.primary_button]
      text = "Partner with us"
      url = "/contact/how-to-engage/"
    [params.cta.secondary_button]
      text = "Learn about participation"
      url = "/careers/"
  
  # Social Media Links
  [params.social]
    twitter = "https://x.com/IndiImpact"
    youtube = "https://www.youtube.com/NovaInstitute"
    github = "https://github.com/independentimpact"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "Features"
    column_2_title = "Organisation"
    column_3_title = "Legal"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Logo configuration
    [params.header.logo]
      src = "/images/logo.svg"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        item_padding = "px-8 py-3"
        background = "bg-white"
        border = "border border-gray-100"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_color = "text-gray-700"
        hover_background = "hover:bg-gray-50"
        text_size = "text-sm"
    
    # Button configuration
    [params.header.buttons]
      # Sign In button
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "#"

      # Get Started button
      [params.header.buttons.getStarted]
        text = "Participate"
        url = "/careers/"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Blog"
    subtitle = "More on our philosophy and roadmap"
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Posts"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Categories"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Popular Tags"
        count = 20

      # Subscribe form section
      [params.blog.sidebar.subscribe]
        enable = true
        title = "Subscribe to Newsletter"
        description = "Get the latest posts delivered right to your inbox"
        action = "https://formspree.io/f/your-form-id"
        emailName = "email"
        buttonText = "Subscribe"
        placeholder = "Enter your email"
        disclaimer = "We respect your privacy. Unsubscribe at any time."

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Impact Framework"
    url = "/impact-framework/"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Design System", url = "/impact-framework/design-system/" },
        { name = "Architectural Principles", url = "/impact-framework/architectural-principles/" },
        { name = "Technical Architecture", url = "/impact-framework/technical-architecture/" },
        { name = "Active Capabilities & Roadmap", url = "/impact-framework/active-capabilities-and-roadmap/" }
      ]
  [[menu.main]]
    name = "Our Story"
    url = "/our-story/"
    weight = 2
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Why Independent Impact", url = "/our-story/why-independent-impact/" },
        { name = "Nova’s Impact Journey", url = "/our-story/nova-impact-journey/" },
        { name = "Team", url = "/our-story/team/" },
        { name = "History", url = "/our-story/history/" }
      ]
  [[menu.main]]
    name = "Get Started"
    url = "/get-started/"
    weight = 3
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Project Implementers & Developers", url = "/get-started/project-implementers/" },
        { name = "Methodology Creators", url = "/get-started/methodology-creators/" },
        { name = "Peer Validators", url = "/get-started/peer-validators/" },
        { name = "Field Verifiers", url = "/get-started/field-verifiers/" },
        { name = "Regulators & Funders", url = "/get-started/regulators-and-funders/" }
      ]
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Impact Indicators & Methods", url = "/resources/impact-indicators-and-methods/" },
        { name = "Blog", url = "/blog/" }
      ]
  [[menu.main]]
    name = "Contact"
    url = "/contact/how-to-engage/"
    weight = 5

  # Footer Column 1 Menu
  [[menu.footer_column_1]]
    name = "Design System"
    url = "/impact-framework/design-system/"
    weight = 1
  [[menu.footer_column_1]]
    name = "Architectural Principles"
    url = "/impact-framework/architectural-principles/"
    weight = 2
  [[menu.footer_column_1]]
    name = "Technical Architecture"
    url = "/impact-framework/technical-architecture/"
    weight = 3
  [[menu.footer_column_1]]
    name = "Active Capabilities & Roadmap"
    url = "/impact-framework/active-capabilities-and-roadmap/"
    weight = 4

  # Footer Column 2 Menu
  [[menu.footer_column_2]]
    name = "Why Independent Impact"
    url = "/our-story/why-independent-impact/"
    weight = 1
  [[menu.footer_column_2]]
    name = "Nova’s Impact Journey"
    url = "/our-story/nova-impact-journey/"
    weight = 2
  [[menu.footer_column_2]]
    name = "Team"
    url = "/our-story/team/"
    weight = 3
  [[menu.footer_column_2]]
    name = "History"
    url = "/our-story/history/"
    weight = 4

  # Footer Column 3 Menu
  [[menu.footer_column_3]]
    name = "Project Implementers & Developers"
    url = "/get-started/project-implementers/"
    weight = 1
  [[menu.footer_column_3]]
    name = "Peer Validators"
    url = "/get-started/peer-validators/"
    weight = 2
  [[menu.footer_column_3]]
    name = "Methodology Creators"
    url = "/get-started/methodology-creators/"
    weight = 3
  [[menu.footer_column_3]]
    name = "Contact"
    url = "/contact/how-to-engage/"
    weight = 4
  [[menu.footer_column_3]]
    name = "Terms & licensing"
    url = "/license"
    weight = 5
  [[menu.footer_column_3]]
    name = "Data stewardship"
    url = "/privacy"
    weight = 6
