name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      - name: Run codespell
        run: |
          codespell \
            --skip="*.png,*.jpg,node_modules,public,package-lock.json" \
            --ignore-words-list="hod,crate" \
            --check-filenames
